#ifndef CONFIG_H
#define CONFIG_H

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

#define SERVER_TICK_MS 10

#define ENABLE_BGM true

#define MAX_CLIENTS 4

#define FIELD_HEIGHT 200
#define FIELD_WIDTH 120
#define FIELD_COLS 8
#define GRID_SIZE ((float)FIELD_WIDTH / FIELD_COLS)

#define TARGET_FPS 120

#define INPUT_GAMEPAD_DEADZONE 0.1f

#define PLAYER_SPEED 50.0f
#define PLAYER_ACCEL 0.1f

#define BULLET_SPEED 150.0f
#define ENEMY_BULLET_SPEED 50.0f

#define ENEMY_SPEED 5.0f

// Time it takes an enemy to move one row, in seconds
#define ROW_TIME (GRID_SIZE / ENEMY_SPEED)

#define BOSS_TIME (ROW_TIME * 30)
#define N_BOSSES 3

#define BOSS_ARC_BULLETS 45
#define BOSS_ARC_COOLDOWN 0.1f
#define BOSS_HOMING_BULLETS 25
#define BOSS_HOMING_COOLDOWN 0.1f
#define BOSS_SPIRAL_BULLETS 360
#define BOSS_SPIRAL_COOLDOWN 0.005f

#define DMG_NUMBER_SIZE 20.0f
#define DMG_NUMBER_TTL 0.5f
#define DMG_NUMBER_SPEED 10.0f
#define DMG_NUMBER_ACCEL (-DMG_NUMBER_SPEED / DMG_NUMBER_TTL)

#define XP_PICKUP_RANGE 2.0f
#define XP_MAGNET_RANGE 25.0f
#define XP_MAGNET_POWER 10.0f

#define MAX_SPECIAL_BULLETS 3
#define LEVEL_UP_OPTIONS 3

#define POWERUP_DURATION 5.0f
#define POWERUP_SPAWN_PROB 0.05f

#define EXPLOSION_TTL 0.8f
#define LASER_TTL 0.5f

#define DMG_FLASH_TIME 0.1f

#define CAMERA_SHAKE_DECAY 80
#define EXPLOSION_CAMERA_SHAKE 0.7

#endif
